# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc88201609f46a82307847bf4dc457641f081caad176f41507e3a9fd4dee0c3acd6ba2383c238b22be350e2ed3ba88f4ec0b763716fdd0143c6d46ea5981569b

test:
  secret_key_base: 25b8f9dfe992d3d1f6c57e3fde0185eb02d43419120eb6066983cd173935f395ca4de7c91bba5abb0c39eccb632c87ceb79b420fac21a5f1e33912c289353281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
